// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmass_skellam2_fcop_cpp
NumericVector dmass_skellam2_fcop_cpp(NumericVector Z1, NumericVector Z2, double mu1, double mu2, double sigma1, double sigma2, double theta, Function pskellam2);
RcppExport SEXP _statman_dmass_skellam2_fcop_cpp(SEXP Z1SEXP, SEXP Z2SEXP, SEXP mu1SEXP, SEXP mu2SEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP thetaSEXP, SEXP pskellam2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Z1(Z1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z2(Z2SEXP);
    Rcpp::traits::input_parameter< double >::type mu1(mu1SEXP);
    Rcpp::traits::input_parameter< double >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Function >::type pskellam2(pskellam2SEXP);
    rcpp_result_gen = Rcpp::wrap(dmass_skellam2_fcop_cpp(Z1, Z2, mu1, mu2, sigma1, sigma2, theta, pskellam2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_statman_dmass_skellam2_fcop_cpp", (DL_FUNC) &_statman_dmass_skellam2_fcop_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_statman(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
