# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmass_skellam2_fcop_cpp <- function(Z1, Z2, mu1, mu2, sigma1, sigma2, theta, pskellam2) {
    .Call(`_statman_dmass_skellam2_fcop_cpp`, Z1, Z2, mu1, mu2, sigma1, sigma2, theta, pskellam2)
}

